{% set name = "objconv" %}
{% set version = "2.54" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/staticfloat/objconv/archive/v{{ version }}.tar.gz
  sha256: db2ec0ea1ab0217e28dcd09217f614ff9c390eb7b6fc7cf0ea0fd0803b165f53

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - make

test:
  commands:
    - objconv -h

about:
  home: https://www.agner.org/optimize/#objconv
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE.txt
  summary: 'Object file converter'

extra:
  recipe-maintainers:
    - isuruf
    - ngam
