{% set name = "objconv" %}
{% set version = "2.53" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/staticfloat/objconv/archive/v{{ version }}.tar.gz
  sha256: a8caa9aaa7d1a9a836eef2f1da6a26cd6e65d046dc0f057eebac930baba7801c

build:
  number: 1
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - make

test:
  commands:
    - objconv -h

about:
  home: https://www.agner.org/optimize/#objconv
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE.txt
  summary: 'Object file converter'

extra:
  recipe-maintainers:
    - isuruf
    - ngam
